logging:
    level:
        com:
            zaxxer:
                hikari: TRACE
                hikari.HikariConfig: DEBUG
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
#        hikari:
#            max-lifetime: 300000
        username: root
        password: Xcode-123
        url: jdbc:mysql://127.0.0.1:3306/xcodev?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#        url: jdbc:mysql://localhost/xcodev?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    mail:
        host: smtp.gmail.com
        port: 587
        username: xcodeid200@gmail.com
        password: diwfuc-1zirmi-jYttap
        properties:
            mail:
                smtp:
                    auth: true
                    connectiontimeout: 5000
                    timeout: 5000
                    writetimeout: 5000
                    starttls:
                        enable: true
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
        generate-ddl: true
    main:
        allow-bean-definition-overriding: true