spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        username: xcodecom_user
        password: 'Q)&lFe5LQ#tC'
        url: jdbc:mysql://xcodev.my.id:3306/xcodecom_db
        hikari:
            max-lifetime: 600000
            maximum-pool-size: 10
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
    main:
        allow-bean-definition-overriding: true
