spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: ''
        url: jdbc:mysql://localhost:3307/bookstore?useSSL=false
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
    main:
        allow-bean-definition-overriding: true
