logging:
    level:
        com:
            zaxxer:
                hikari: TRACE
                hikari.HikariConfig: DEBUG
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        username: ENC(Te/HiLESkKgrvPIThZ3Yzg==)
        password: ENC(eqxpsnpiLriw7Z3bsS3/a3bfDRmkWB7RyrlA1m0ynys=)
        url: ENC(Nm0Av1XQ7V5sqK9wtBpUbTzD2qZrOtsu6xJs9t9+Nwd2xN9cRMI0SLCWK/7N/CzMjcpuGQ7/BzckA88b17c0dNJ1EDT56B1K)
    mail:
        host: smtp.gmail.com
        port: 587
        username: ENC(WQ4A2Wa4SM03oCvM/HwoLLxoNmCHhSIIULdES5nps8U=)
        password: ENC(yaLtsFlWc43QNyE3McGcaDsNuL1vlVpzEG1YH/nvY2c=)
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        protocol: smtp
        test-connection: false
        default-encoding: utf-8
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: false
        generate-ddl: false
    main:
        allow-bean-definition-overriding: true
jasypt:
    encryptor:
        algorithm: PBEWithMD5AndDES
        iv-generator-classname: org.jasypt.iv.NoIvGenerator
xendit:
    token: ENC(/n6LplARZeQHl1JXFq3kS6Nj0SwFHK+wej7kClLSCgiH3Vl0DGLPk1hO3aLa/U86XhUYmocOTCVlRyr4oyXsVDj0JiJI8E5IWSGttTrxxuFL+Kcrvzkd/8GqLoE1mZmX)
    callback: ENC(0byBPs4X5IDFvlKLW9znS/fZywFR+OUyLw+9WeLAsk745pWTFGqu4N/z8zZ0hNw/zRYWeSpGg97jdeQvkWFX3w==)