logging:
    level:
        com:
            zaxxer:
                hikari: TRACE
                hikari.HikariConfig: DEBUG
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
#        hikari:
#            max-lifetime: 300000
        username: root
        password: +J4LMJ75Q)p!
        url: jdbc:mysql://localhost:3306/xcodev?useSSL=false
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
    main:
        allow-bean-definition-overriding: true
