logging:
    level:
        com:
            zaxxer:
                hikari: TRACE
                hikari.HikariConfig: DEBUG
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        hikari:
            max-lifetime: 300000
        password: Q)&lFe5LQ#tC
        url: jdbc:mysql://xcodev.my.id:3306/xcodecom_db
        username: xcodecom_user
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
    main:
        allow-bean-definition-overriding: true
